# Generated by Django 2.2 on 2019-05-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'Cancelado'), (1, 'Aprovado'), (0, 'Pendente')], default=0, verbose_name='Situação'),
        ),
    ]
